ci: fix deployment error
Problem:
Error: Ensure GITHUB_TOKEN has permission "id-token: write".

Don't know why the permission fails even if id-token is set up
write. So only deploy to pages from main branch.