fix(asterinas): run_with_tcx requires hidden run_driver!
error: cannot find macro `run_driver` in this scope
  --> src/bin/safety-tool/main.rs:72:15
   |
72 |       let res = run_with_tcx!(rustc_args, |tcx| {

   |  _______________^
73 | |         analyze_hir::analyze_hir(tcx);
74 | |         analyze(tcx);
75 | |         compilation_status()
76 | |     });
   | |______^
   |
   = note: this error originates in the macro `run_with_tcx` (in Nightly builds, run with -Z macro-backtrace for more info)