cargo-safety-tool: abort instead of panic for run
This simplifies error output. Currely as follows

error: Tag is not discharged: `NonNull`
  --> src/main.rs:23:5
   |
23 |     let val = unsafe { a.get() };
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ For this unsafe call.
   |

Total counts of diagnostics from safety-tool: {MissingDischarge: 1}

error: could not compile `demo` (bin "demo")

Caused by:
  process didn't exit successfully: `cargo-safety-tool --crate-name demo --edition=2024 src/main.rs --error-format=json --json=diagnostic-rend
ered-ansi,artifacts,future-incompat --diagnostic-width=142 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --check-cf
g 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=531908ee13a22a5b -C extra-filename=-67bed40decd9cd52 --out-dir /home/gh-
zjp-CN/tag-std/safety-tool/tests/basic/target/debug/deps -C incremental=/home/gh-zjp-CN/tag-std/safety-tool/tests/basic/target/debug/increment
al -L dependency=/home/gh-zjp-CN/tag-std/safety-tool/tests/basic/target/debug/deps --extern demo=/home/gh-zjp-CN/tag-std/safety-tool/tests/bas
ic/target/debug/deps/libdemo-0429d6a363c97b9e.rlib --extern safety_macro=/home/gh-zjp-CN/tag-std/safety-tool/tests/basic/target/debug/deps/lib
safety_macro-5a86840c05e0106b.so` (signal: 6, SIGABRT: process abort signal)
fish: Job 1, 'cargo safety-tool' terminated by signal SIGABRT (Abort)