feat: check missing unsafe property
error: `UserProperty` is not discharged
  --> src/main.rs:9:31
   |
 6 | fn main() {
 7 |     let (p, l, _c) = Vec::new().into_raw_parts();
 8 |     let a = MyStruct::from(p, l);
 9 |     println!("{:?}", unsafe { a.get() });
   |                               ^^^^^^^ For this unsafe call.
10 | }
   |